HW6 - Указатели
simonnik/gb_go_level_1 pull request #6
Opened 2021-08-28 02:59 UTC by simonnik

2021-09-06 15:25 UTC, goarchitecture requested changes

2021-09-06 15:25 UTC, goarchitecture commented on hw6/answers.md
> +При работе со slice, map.
верно

2021-09-06 15:25 UTC, goarchitecture commented on hw6/answers.md
> +В задании 3 (простые числа) - в функцию append можно было передать слайс используя указатель.
аппенд очень редко используется с указателем. Только если нужные какие-то хирые-хитрые вещи.

Почти в каждом задании мы используем функцию, в которой передается значения по указателю. И если передавать не по указателю, то всё сломается. что это за функция?

2021-09-06 15:25 UTC, goarchitecture commented on hw6/answers.md
> +При умножении присутствуют 2 операнда. При разыменовании указателя - 1.
да, верно. А ещё что может знать компилятор и по каким критериям решать?

2021-09-06 15:38 UTC, goarchitecture commented on hw6/answers.md
> +При умножении присутствуют 2 операнда. При разыменовании указателя - 1.
Возможна ли такая запись в go?
```
x := a**b
```
а такая
```
x := a***b
```

Если да, то как компилятор помогает, что есть что в этих звёздочках?

2021-09-07 20:15 UTC, simonnik commented on hw6/answers.md
> +В задании 3 (простые числа) - в функцию append можно было передать слайс используя указатель.
fmt.Scan?

2021-09-07 20:58 UTC, simonnik commented on hw6/answers.md
> +При умножении присутствуют 2 операнда. При разыменовании указателя - 1.
Умножение является инфиксным оператором, в то время как оператор разыменования является префиксным
Поэтому компилятор понимает во-первых какие типы у переменных, во-вторых какой используется оператор. В приоритете проверяется умножение, т.е. пример 
```
a := 2
b:=&a
x := a*b
```

выдаст ошибку потому что типы разные, но при этом применяется  оператор умножения

Такая запись возможна
```
x := a**b
```
потому что правила соблюдены

С такой записью по сложнее

```
x := a***b
```
тут если расписать получается следующее

```
x := int * (**b)
```
т.е. мы пытаемся разыменовать переменную аж 2 раза, на что компилятор и ругнется

Так можно писать если только добавить `&` 

```
x := a**&*b
```

2021-09-07 20:58 UTC, simonnik commented on hw6/answers.md
> +При умножении присутствуют 2 операнда. При разыменовании указателя - 1.
> да, верно. А ещё что может знать компилятор и по каким критериям решать?

Умножение является инфиксным оператором, в то время как оператор разыменования является префиксным
Поэтому компилятор понимает во-первых какие типы у переменных, во-вторых какой используется оператор. В приоритете проверяется умножение, т.е. пример 
```
a := 2
b:=&a
x := a*b
```

выдаст ошибку потому что типы разные, но при этом применяется  оператор умножения

2021-09-17 02:13 UTC, merged